server:
  servlet:
    context-path: /api/v1
#  port: 5000
spring:
  datasource:
    password: 12345
    url: jdbc:mysql://localhost:3306/tkt_bkng?createDatabaseIfNotExist=true
    username: mg

#Amazon aws
#spring:
#  datasource:
#    password: 12345678
#    url: jdbc:mysql://mgdb.ckjckuer8nk1.us-east-1.rds.amazonaws.com:3306/tkt_bkng?createDatabaseIfNotExist=true
#    username: mg
#spring:
#  datasource:
#    password: ${JDBC_DATABASE_PASSWORD}
#    url: ${JDBC_DATABASE_URL}
#    username: ${JDBC_DATABASE_USERNAME}
#    driver-class-name: org.postgresql.Driver

#spring:
#  datasource:
#    password: 12345
#    url: jdbc:postgresql://localhost/postgres
#    username: postgres
#    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-bean-definition-overriding: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
jwt:
 secret: mg123
    
#   jwt.secret=mg123